<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Sudah_kontrol extends CI_Controller
{
    
        
    function __construct()
    {
        parent::__construct();
        $this->load->model('Sudah_kontrol_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $sudah_kontrol = $this->Sudah_kontrol_model->get_all();

        $data = array(
            'sudah_kontrol_data' => $sudah_kontrol
        );

        $this->template->load('template','sudah/view_kontrol_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Sudah_kontrol_model->get_by_id($id);
        if ($row) {
            $data = array(
		'no_rm' => $row->no_rm,
		'tanggal' => $row->tanggal,
		'no_kontrol' => $row->no_kontrol,
		'tanggal_kontrol' => $row->tanggal_kontrol,
		'dokter' => $row->dokter,
		'spesialis' => $row->spesialis,
		'keterangan' => $row->keterangan,
	    );
            $this->template->load('template','sudah/view_kontrol_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('sudah_kontrol'));
        }
    }

    public function word()
    {
        header("Content-type: application/vnd.ms-word");
        header("Content-Disposition: attachment;Filename=view_kontrol.doc");

        $data = array(
            'view_kontrol_data' => $this->Sudah_kontrol_model->get_all(),
            'start' => 0
        );
        
        $this->load->view('sudah/view_kontrol_doc',$data);
    }

}

/* End of file Sudah_kontrol.php */
/* Location: ./application/controllers/Sudah_kontrol.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-22 22:58:26 */
/* http://harviacode.com */