<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kontrol_model extends CI_Model
{

    public $table = 'kontrol';
    public $id = 'id';
    public $order = 'DESC';
    public $select = 'kontrol.*, dokter.nama, dokter.spesialis';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select($this->select);
        $this->db->join('dokter', 'dokter.id=kontrol.id_dokter');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        // $this->db->select($this->select);
        // $this->db->join('dokter', 'dokter.id=kontrol.id_dokter');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('id_dokter', $q);
	$this->db->or_like('no_rm', $q);
	$this->db->or_like('no_kontrol', $q);
	$this->db->or_like('tgl_kontrol', $q);
	$this->db->or_like('ket', $q);
    $this->db->or_like('created', $q);
    $this->db->select($this->select);
    $this->db->join('dokter', 'dokter.id=kontrol.id_dokter');
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->select($this->select);
        $this->db->join('dokter', 'dokter.id=kontrol.id_dokter');
        $this->db->like('id', $q);
	$this->db->or_like('id_dokter', $q);
	$this->db->or_like('no_rm', $q);
	$this->db->or_like('no_kontrol', $q);
	$this->db->or_like('tgl_kontrol', $q);
	$this->db->or_like('ket', $q);
	$this->db->or_like('created', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Kontrol_model.php */
/* Location: ./application/models/Kontrol_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-22 22:59:07 */
/* http://harviacode.com */